// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: asr_engine.proto

package qwen_asr

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SessionConfig struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Language        string                 `protobuf:"bytes,1,opt,name=language,proto3" json:"language,omitempty"`                                         // 强制语种，空 = 自动检测
	Context         string                 `protobuf:"bytes,2,opt,name=context,proto3" json:"context,omitempty"`                                           // 上下文提示
	SampleRate      int32                  `protobuf:"varint,3,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"`                  // 音频采样率，默认 16000
	Encoding        string                 `protobuf:"bytes,4,opt,name=encoding,proto3" json:"encoding,omitempty"`                                         // "pcm_f32le" | "pcm_s16le"
	ChunkSizeSec    float32                `protobuf:"fixed32,5,opt,name=chunk_size_sec,json=chunkSizeSec,proto3" json:"chunk_size_sec,omitempty"`         // 模型 chunk 大小（秒）
	UnfixedChunkNum int32                  `protobuf:"varint,6,opt,name=unfixed_chunk_num,json=unfixedChunkNum,proto3" json:"unfixed_chunk_num,omitempty"` // unfixed chunk 数量
	UnfixedTokenNum int32                  `protobuf:"varint,7,opt,name=unfixed_token_num,json=unfixedTokenNum,proto3" json:"unfixed_token_num,omitempty"` // unfixed token 数量
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SessionConfig) Reset() {
	*x = SessionConfig{}
	mi := &file_asr_engine_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionConfig) ProtoMessage() {}

func (x *SessionConfig) ProtoReflect() protoreflect.Message {
	mi := &file_asr_engine_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionConfig.ProtoReflect.Descriptor instead.
func (*SessionConfig) Descriptor() ([]byte, []int) {
	return file_asr_engine_proto_rawDescGZIP(), []int{0}
}

func (x *SessionConfig) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *SessionConfig) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

func (x *SessionConfig) GetSampleRate() int32 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

func (x *SessionConfig) GetEncoding() string {
	if x != nil {
		return x.Encoding
	}
	return ""
}

func (x *SessionConfig) GetChunkSizeSec() float32 {
	if x != nil {
		return x.ChunkSizeSec
	}
	return 0
}

func (x *SessionConfig) GetUnfixedChunkNum() int32 {
	if x != nil {
		return x.UnfixedChunkNum
	}
	return 0
}

func (x *SessionConfig) GetUnfixedTokenNum() int32 {
	if x != nil {
		return x.UnfixedTokenNum
	}
	return 0
}

type CreateSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Config        *SessionConfig         `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionRequest) Reset() {
	*x = CreateSessionRequest{}
	mi := &file_asr_engine_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionRequest) ProtoMessage() {}

func (x *CreateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_asr_engine_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateSessionRequest) Descriptor() ([]byte, []int) {
	return file_asr_engine_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CreateSessionRequest) GetConfig() *SessionConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type CreateSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionResponse) Reset() {
	*x = CreateSessionResponse{}
	mi := &file_asr_engine_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionResponse) ProtoMessage() {}

func (x *CreateSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_asr_engine_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionResponse.ProtoReflect.Descriptor instead.
func (*CreateSessionResponse) Descriptor() ([]byte, []int) {
	return file_asr_engine_proto_rawDescGZIP(), []int{2}
}

func (x *CreateSessionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateSessionResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type PushAudioRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	AudioData     []byte                 `protobuf:"bytes,2,opt,name=audio_data,json=audioData,proto3" json:"audio_data,omitempty"` // 原始 PCM 字节
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushAudioRequest) Reset() {
	*x = PushAudioRequest{}
	mi := &file_asr_engine_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushAudioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushAudioRequest) ProtoMessage() {}

func (x *PushAudioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_asr_engine_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushAudioRequest.ProtoReflect.Descriptor instead.
func (*PushAudioRequest) Descriptor() ([]byte, []int) {
	return file_asr_engine_proto_rawDescGZIP(), []int{3}
}

func (x *PushAudioRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *PushAudioRequest) GetAudioData() []byte {
	if x != nil {
		return x.AudioData
	}
	return nil
}

type PushAudioResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Language      string                 `protobuf:"bytes,1,opt,name=language,proto3" json:"language,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Updated       bool                   `protobuf:"varint,3,opt,name=updated,proto3" json:"updated,omitempty"` // 是否产生了新的推理结果（buffer 未满时为 false）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushAudioResponse) Reset() {
	*x = PushAudioResponse{}
	mi := &file_asr_engine_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushAudioResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushAudioResponse) ProtoMessage() {}

func (x *PushAudioResponse) ProtoReflect() protoreflect.Message {
	mi := &file_asr_engine_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushAudioResponse.ProtoReflect.Descriptor instead.
func (*PushAudioResponse) Descriptor() ([]byte, []int) {
	return file_asr_engine_proto_rawDescGZIP(), []int{4}
}

func (x *PushAudioResponse) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *PushAudioResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *PushAudioResponse) GetUpdated() bool {
	if x != nil {
		return x.Updated
	}
	return false
}

type FinishSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinishSessionRequest) Reset() {
	*x = FinishSessionRequest{}
	mi := &file_asr_engine_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinishSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishSessionRequest) ProtoMessage() {}

func (x *FinishSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_asr_engine_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishSessionRequest.ProtoReflect.Descriptor instead.
func (*FinishSessionRequest) Descriptor() ([]byte, []int) {
	return file_asr_engine_proto_rawDescGZIP(), []int{5}
}

func (x *FinishSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type FinishSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Language      string                 `protobuf:"bytes,1,opt,name=language,proto3" json:"language,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinishSessionResponse) Reset() {
	*x = FinishSessionResponse{}
	mi := &file_asr_engine_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinishSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishSessionResponse) ProtoMessage() {}

func (x *FinishSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_asr_engine_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishSessionResponse.ProtoReflect.Descriptor instead.
func (*FinishSessionResponse) Descriptor() ([]byte, []int) {
	return file_asr_engine_proto_rawDescGZIP(), []int{6}
}

func (x *FinishSessionResponse) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *FinishSessionResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type DestroySessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroySessionRequest) Reset() {
	*x = DestroySessionRequest{}
	mi := &file_asr_engine_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroySessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroySessionRequest) ProtoMessage() {}

func (x *DestroySessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_asr_engine_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroySessionRequest.ProtoReflect.Descriptor instead.
func (*DestroySessionRequest) Descriptor() ([]byte, []int) {
	return file_asr_engine_proto_rawDescGZIP(), []int{7}
}

func (x *DestroySessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type DestroySessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroySessionResponse) Reset() {
	*x = DestroySessionResponse{}
	mi := &file_asr_engine_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroySessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroySessionResponse) ProtoMessage() {}

func (x *DestroySessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_asr_engine_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroySessionResponse.ProtoReflect.Descriptor instead.
func (*DestroySessionResponse) Descriptor() ([]byte, []int) {
	return file_asr_engine_proto_rawDescGZIP(), []int{8}
}

func (x *DestroySessionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_asr_engine_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_asr_engine_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_asr_engine_proto_rawDescGZIP(), []int{9}
}

type HealthCheckResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ActiveSessions   int32                  `protobuf:"varint,1,opt,name=active_sessions,json=activeSessions,proto3" json:"active_sessions,omitempty"`
	MaxSessions      int32                  `protobuf:"varint,2,opt,name=max_sessions,json=maxSessions,proto3" json:"max_sessions,omitempty"`
	ModelLoaded      bool                   `protobuf:"varint,3,opt,name=model_loaded,json=modelLoaded,proto3" json:"model_loaded,omitempty"`
	GpuMemoryUsedPct float32                `protobuf:"fixed32,4,opt,name=gpu_memory_used_pct,json=gpuMemoryUsedPct,proto3" json:"gpu_memory_used_pct,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_asr_engine_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_asr_engine_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_asr_engine_proto_rawDescGZIP(), []int{10}
}

func (x *HealthCheckResponse) GetActiveSessions() int32 {
	if x != nil {
		return x.ActiveSessions
	}
	return 0
}

func (x *HealthCheckResponse) GetMaxSessions() int32 {
	if x != nil {
		return x.MaxSessions
	}
	return 0
}

func (x *HealthCheckResponse) GetModelLoaded() bool {
	if x != nil {
		return x.ModelLoaded
	}
	return false
}

func (x *HealthCheckResponse) GetGpuMemoryUsedPct() float32 {
	if x != nil {
		return x.GpuMemoryUsedPct
	}
	return 0
}

var File_asr_engine_proto protoreflect.FileDescriptor

const file_asr_engine_proto_rawDesc = "" +
	"\n" +
	"\x10asr_engine.proto\x12\bqwen_asr\"\x80\x02\n" +
	"\rSessionConfig\x12\x1a\n" +
	"\blanguage\x18\x01 \x01(\tR\blanguage\x12\x18\n" +
	"\acontext\x18\x02 \x01(\tR\acontext\x12\x1f\n" +
	"\vsample_rate\x18\x03 \x01(\x05R\n" +
	"sampleRate\x12\x1a\n" +
	"\bencoding\x18\x04 \x01(\tR\bencoding\x12$\n" +
	"\x0echunk_size_sec\x18\x05 \x01(\x02R\fchunkSizeSec\x12*\n" +
	"\x11unfixed_chunk_num\x18\x06 \x01(\x05R\x0funfixedChunkNum\x12*\n" +
	"\x11unfixed_token_num\x18\a \x01(\x05R\x0funfixedTokenNum\"f\n" +
	"\x14CreateSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12/\n" +
	"\x06config\x18\x02 \x01(\v2\x17.qwen_asr.SessionConfigR\x06config\"V\n" +
	"\x15CreateSessionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"P\n" +
	"\x10PushAudioRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"audio_data\x18\x02 \x01(\fR\taudioData\"]\n" +
	"\x11PushAudioResponse\x12\x1a\n" +
	"\blanguage\x18\x01 \x01(\tR\blanguage\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x18\n" +
	"\aupdated\x18\x03 \x01(\bR\aupdated\"5\n" +
	"\x14FinishSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"G\n" +
	"\x15FinishSessionResponse\x12\x1a\n" +
	"\blanguage\x18\x01 \x01(\tR\blanguage\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"6\n" +
	"\x15DestroySessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"2\n" +
	"\x16DestroySessionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x14\n" +
	"\x12HealthCheckRequest\"\xb3\x01\n" +
	"\x13HealthCheckResponse\x12'\n" +
	"\x0factive_sessions\x18\x01 \x01(\x05R\x0eactiveSessions\x12!\n" +
	"\fmax_sessions\x18\x02 \x01(\x05R\vmaxSessions\x12!\n" +
	"\fmodel_loaded\x18\x03 \x01(\bR\vmodelLoaded\x12-\n" +
	"\x13gpu_memory_used_pct\x18\x04 \x01(\x02R\x10gpuMemoryUsedPct2\x96\x03\n" +
	"\tASREngine\x12P\n" +
	"\rCreateSession\x12\x1e.qwen_asr.CreateSessionRequest\x1a\x1f.qwen_asr.CreateSessionResponse\x12D\n" +
	"\tPushAudio\x12\x1a.qwen_asr.PushAudioRequest\x1a\x1b.qwen_asr.PushAudioResponse\x12P\n" +
	"\rFinishSession\x12\x1e.qwen_asr.FinishSessionRequest\x1a\x1f.qwen_asr.FinishSessionResponse\x12S\n" +
	"\x0eDestroySession\x12\x1f.qwen_asr.DestroySessionRequest\x1a .qwen_asr.DestroySessionResponse\x12J\n" +
	"\vHealthCheck\x12\x1c.qwen_asr.HealthCheckRequest\x1a\x1d.qwen_asr.HealthCheckResponseB\x18Z\x16gateway/proto/qwen_asrb\x06proto3"

var (
	file_asr_engine_proto_rawDescOnce sync.Once
	file_asr_engine_proto_rawDescData []byte
)

func file_asr_engine_proto_rawDescGZIP() []byte {
	file_asr_engine_proto_rawDescOnce.Do(func() {
		file_asr_engine_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_asr_engine_proto_rawDesc), len(file_asr_engine_proto_rawDesc)))
	})
	return file_asr_engine_proto_rawDescData
}

var file_asr_engine_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_asr_engine_proto_goTypes = []any{
	(*SessionConfig)(nil),          // 0: qwen_asr.SessionConfig
	(*CreateSessionRequest)(nil),   // 1: qwen_asr.CreateSessionRequest
	(*CreateSessionResponse)(nil),  // 2: qwen_asr.CreateSessionResponse
	(*PushAudioRequest)(nil),       // 3: qwen_asr.PushAudioRequest
	(*PushAudioResponse)(nil),      // 4: qwen_asr.PushAudioResponse
	(*FinishSessionRequest)(nil),   // 5: qwen_asr.FinishSessionRequest
	(*FinishSessionResponse)(nil),  // 6: qwen_asr.FinishSessionResponse
	(*DestroySessionRequest)(nil),  // 7: qwen_asr.DestroySessionRequest
	(*DestroySessionResponse)(nil), // 8: qwen_asr.DestroySessionResponse
	(*HealthCheckRequest)(nil),     // 9: qwen_asr.HealthCheckRequest
	(*HealthCheckResponse)(nil),    // 10: qwen_asr.HealthCheckResponse
}
var file_asr_engine_proto_depIdxs = []int32{
	0,  // 0: qwen_asr.CreateSessionRequest.config:type_name -> qwen_asr.SessionConfig
	1,  // 1: qwen_asr.ASREngine.CreateSession:input_type -> qwen_asr.CreateSessionRequest
	3,  // 2: qwen_asr.ASREngine.PushAudio:input_type -> qwen_asr.PushAudioRequest
	5,  // 3: qwen_asr.ASREngine.FinishSession:input_type -> qwen_asr.FinishSessionRequest
	7,  // 4: qwen_asr.ASREngine.DestroySession:input_type -> qwen_asr.DestroySessionRequest
	9,  // 5: qwen_asr.ASREngine.HealthCheck:input_type -> qwen_asr.HealthCheckRequest
	2,  // 6: qwen_asr.ASREngine.CreateSession:output_type -> qwen_asr.CreateSessionResponse
	4,  // 7: qwen_asr.ASREngine.PushAudio:output_type -> qwen_asr.PushAudioResponse
	6,  // 8: qwen_asr.ASREngine.FinishSession:output_type -> qwen_asr.FinishSessionResponse
	8,  // 9: qwen_asr.ASREngine.DestroySession:output_type -> qwen_asr.DestroySessionResponse
	10, // 10: qwen_asr.ASREngine.HealthCheck:output_type -> qwen_asr.HealthCheckResponse
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_asr_engine_proto_init() }
func file_asr_engine_proto_init() {
	if File_asr_engine_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_asr_engine_proto_rawDesc), len(file_asr_engine_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_asr_engine_proto_goTypes,
		DependencyIndexes: file_asr_engine_proto_depIdxs,
		MessageInfos:      file_asr_engine_proto_msgTypes,
	}.Build()
	File_asr_engine_proto = out.File
	file_asr_engine_proto_goTypes = nil
	file_asr_engine_proto_depIdxs = nil
}
