// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: asr_engine.proto

package qwen_asr

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ASREngine_CreateSession_FullMethodName  = "/qwen_asr.ASREngine/CreateSession"
	ASREngine_PushAudio_FullMethodName      = "/qwen_asr.ASREngine/PushAudio"
	ASREngine_FinishSession_FullMethodName  = "/qwen_asr.ASREngine/FinishSession"
	ASREngine_DestroySession_FullMethodName = "/qwen_asr.ASREngine/DestroySession"
	ASREngine_HealthCheck_FullMethodName    = "/qwen_asr.ASREngine/HealthCheck"
)

// ASREngineClient is the client API for ASREngine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ASR Engine gRPC Service
type ASREngineClient interface {
	// 创建一个新的 streaming session
	CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*CreateSessionResponse, error)
	// 推送一段音频数据，返回当前转译结果
	PushAudio(ctx context.Context, in *PushAudioRequest, opts ...grpc.CallOption) (*PushAudioResponse, error)
	// 结束 session，flush 剩余音频，返回最终结果
	FinishSession(ctx context.Context, in *FinishSessionRequest, opts ...grpc.CallOption) (*FinishSessionResponse, error)
	// 销毁 session（异常断开时调用，释放资源）
	DestroySession(ctx context.Context, in *DestroySessionRequest, opts ...grpc.CallOption) (*DestroySessionResponse, error)
	// 健康检查（返回当前 session 数、GPU 利用率等）
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type aSREngineClient struct {
	cc grpc.ClientConnInterface
}

func NewASREngineClient(cc grpc.ClientConnInterface) ASREngineClient {
	return &aSREngineClient{cc}
}

func (c *aSREngineClient) CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*CreateSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSessionResponse)
	err := c.cc.Invoke(ctx, ASREngine_CreateSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aSREngineClient) PushAudio(ctx context.Context, in *PushAudioRequest, opts ...grpc.CallOption) (*PushAudioResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PushAudioResponse)
	err := c.cc.Invoke(ctx, ASREngine_PushAudio_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aSREngineClient) FinishSession(ctx context.Context, in *FinishSessionRequest, opts ...grpc.CallOption) (*FinishSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FinishSessionResponse)
	err := c.cc.Invoke(ctx, ASREngine_FinishSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aSREngineClient) DestroySession(ctx context.Context, in *DestroySessionRequest, opts ...grpc.CallOption) (*DestroySessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DestroySessionResponse)
	err := c.cc.Invoke(ctx, ASREngine_DestroySession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aSREngineClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, ASREngine_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ASREngineServer is the server API for ASREngine service.
// All implementations must embed UnimplementedASREngineServer
// for forward compatibility.
//
// ASR Engine gRPC Service
type ASREngineServer interface {
	// 创建一个新的 streaming session
	CreateSession(context.Context, *CreateSessionRequest) (*CreateSessionResponse, error)
	// 推送一段音频数据，返回当前转译结果
	PushAudio(context.Context, *PushAudioRequest) (*PushAudioResponse, error)
	// 结束 session，flush 剩余音频，返回最终结果
	FinishSession(context.Context, *FinishSessionRequest) (*FinishSessionResponse, error)
	// 销毁 session（异常断开时调用，释放资源）
	DestroySession(context.Context, *DestroySessionRequest) (*DestroySessionResponse, error)
	// 健康检查（返回当前 session 数、GPU 利用率等）
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedASREngineServer()
}

// UnimplementedASREngineServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedASREngineServer struct{}

func (UnimplementedASREngineServer) CreateSession(context.Context, *CreateSessionRequest) (*CreateSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSession not implemented")
}
func (UnimplementedASREngineServer) PushAudio(context.Context, *PushAudioRequest) (*PushAudioResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PushAudio not implemented")
}
func (UnimplementedASREngineServer) FinishSession(context.Context, *FinishSessionRequest) (*FinishSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FinishSession not implemented")
}
func (UnimplementedASREngineServer) DestroySession(context.Context, *DestroySessionRequest) (*DestroySessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DestroySession not implemented")
}
func (UnimplementedASREngineServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedASREngineServer) mustEmbedUnimplementedASREngineServer() {}
func (UnimplementedASREngineServer) testEmbeddedByValue()                   {}

// UnsafeASREngineServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ASREngineServer will
// result in compilation errors.
type UnsafeASREngineServer interface {
	mustEmbedUnimplementedASREngineServer()
}

func RegisterASREngineServer(s grpc.ServiceRegistrar, srv ASREngineServer) {
	// If the following call pancis, it indicates UnimplementedASREngineServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ASREngine_ServiceDesc, srv)
}

func _ASREngine_CreateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ASREngineServer).CreateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ASREngine_CreateSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ASREngineServer).CreateSession(ctx, req.(*CreateSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ASREngine_PushAudio_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushAudioRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ASREngineServer).PushAudio(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ASREngine_PushAudio_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ASREngineServer).PushAudio(ctx, req.(*PushAudioRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ASREngine_FinishSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FinishSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ASREngineServer).FinishSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ASREngine_FinishSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ASREngineServer).FinishSession(ctx, req.(*FinishSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ASREngine_DestroySession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DestroySessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ASREngineServer).DestroySession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ASREngine_DestroySession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ASREngineServer).DestroySession(ctx, req.(*DestroySessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ASREngine_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ASREngineServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ASREngine_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ASREngineServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ASREngine_ServiceDesc is the grpc.ServiceDesc for ASREngine service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ASREngine_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "qwen_asr.ASREngine",
	HandlerType: (*ASREngineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSession",
			Handler:    _ASREngine_CreateSession_Handler,
		},
		{
			MethodName: "PushAudio",
			Handler:    _ASREngine_PushAudio_Handler,
		},
		{
			MethodName: "FinishSession",
			Handler:    _ASREngine_FinishSession_Handler,
		},
		{
			MethodName: "DestroySession",
			Handler:    _ASREngine_DestroySession_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _ASREngine_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "asr_engine.proto",
}
