# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import asr_engine_pb2 as asr__engine__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in asr_engine_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ASREngineStub(object):
    """ASR Engine gRPC Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateSession = channel.unary_unary(
                '/qwen_asr.ASREngine/CreateSession',
                request_serializer=asr__engine__pb2.CreateSessionRequest.SerializeToString,
                response_deserializer=asr__engine__pb2.CreateSessionResponse.FromString,
                _registered_method=True)
        self.PushAudio = channel.unary_unary(
                '/qwen_asr.ASREngine/PushAudio',
                request_serializer=asr__engine__pb2.PushAudioRequest.SerializeToString,
                response_deserializer=asr__engine__pb2.PushAudioResponse.FromString,
                _registered_method=True)
        self.FinishSession = channel.unary_unary(
                '/qwen_asr.ASREngine/FinishSession',
                request_serializer=asr__engine__pb2.FinishSessionRequest.SerializeToString,
                response_deserializer=asr__engine__pb2.FinishSessionResponse.FromString,
                _registered_method=True)
        self.DestroySession = channel.unary_unary(
                '/qwen_asr.ASREngine/DestroySession',
                request_serializer=asr__engine__pb2.DestroySessionRequest.SerializeToString,
                response_deserializer=asr__engine__pb2.DestroySessionResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/qwen_asr.ASREngine/HealthCheck',
                request_serializer=asr__engine__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=asr__engine__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class ASREngineServicer(object):
    """ASR Engine gRPC Service
    """

    def CreateSession(self, request, context):
        """创建一个新的 streaming session
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PushAudio(self, request, context):
        """推送一段音频数据，返回当前转译结果
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FinishSession(self, request, context):
        """结束 session，flush 剩余音频，返回最终结果
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DestroySession(self, request, context):
        """销毁 session（异常断开时调用，释放资源）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """健康检查（返回当前 session 数、GPU 利用率等）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ASREngineServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSession,
                    request_deserializer=asr__engine__pb2.CreateSessionRequest.FromString,
                    response_serializer=asr__engine__pb2.CreateSessionResponse.SerializeToString,
            ),
            'PushAudio': grpc.unary_unary_rpc_method_handler(
                    servicer.PushAudio,
                    request_deserializer=asr__engine__pb2.PushAudioRequest.FromString,
                    response_serializer=asr__engine__pb2.PushAudioResponse.SerializeToString,
            ),
            'FinishSession': grpc.unary_unary_rpc_method_handler(
                    servicer.FinishSession,
                    request_deserializer=asr__engine__pb2.FinishSessionRequest.FromString,
                    response_serializer=asr__engine__pb2.FinishSessionResponse.SerializeToString,
            ),
            'DestroySession': grpc.unary_unary_rpc_method_handler(
                    servicer.DestroySession,
                    request_deserializer=asr__engine__pb2.DestroySessionRequest.FromString,
                    response_serializer=asr__engine__pb2.DestroySessionResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=asr__engine__pb2.HealthCheckRequest.FromString,
                    response_serializer=asr__engine__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'qwen_asr.ASREngine', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('qwen_asr.ASREngine', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ASREngine(object):
    """ASR Engine gRPC Service
    """

    @staticmethod
    def CreateSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qwen_asr.ASREngine/CreateSession',
            asr__engine__pb2.CreateSessionRequest.SerializeToString,
            asr__engine__pb2.CreateSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PushAudio(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qwen_asr.ASREngine/PushAudio',
            asr__engine__pb2.PushAudioRequest.SerializeToString,
            asr__engine__pb2.PushAudioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FinishSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qwen_asr.ASREngine/FinishSession',
            asr__engine__pb2.FinishSessionRequest.SerializeToString,
            asr__engine__pb2.FinishSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DestroySession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qwen_asr.ASREngine/DestroySession',
            asr__engine__pb2.DestroySessionRequest.SerializeToString,
            asr__engine__pb2.DestroySessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qwen_asr.ASREngine/HealthCheck',
            asr__engine__pb2.HealthCheckRequest.SerializeToString,
            asr__engine__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
